trigger:
  paths:
    include:
      - sample_notebook.py

variables:
  - group: DatabricksSecrets

stages:
  - stage: DeployToDatabricks
    displayName: Deploy Notebook to Databricks
    jobs:
      - job: Deploy
        displayName: Upload to Workspace
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'

          - script: |
              pip install databricks-cli
            displayName: 'Install databricks-cli'

          - script: |
              echo -e "[DEFAULT]\nhost = $(DATABRICKS_HOST)\ntoken = $(DATABRICKS_TOKEN)" > ~/.databricks.cfg
              export DATABRICKS_CONFIG_FILE=~/.databricks.cfg

              echo "✅ CLI configured. Now uploading notebook..."

              databricks workspace import \
                "$(Build.SourcesDirectory)/sample_notebook.py" \
                /Shared/sample_notebook \
                --language PYTHON \
                --format SOURCE \
                --overwrite
            displayName: 'Configure CLI & Upload Notebook'
