trigger:
  paths:
    include:
      - sample_notebook.py

variables:
  - group: DatabricksSecrets

stages:
  - stage: DeployToDatabricks
    displayName: Deploy Notebook to Databricks
    jobs:
      - job: Deploy
        displayName: Upload to Workspace
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'

          - script: |
              pip install databricks-cli
            displayName: 'Install databricks-cli'

          - script: |
              mkdir -p /home/vsts/.databricks
              echo -e "[DEFAULT]\nhost = $(DATABRICKS_HOST)\ntoken = $(DATABRICKS_TOKEN)" > /home/vsts/.databricks/config
              export DATABRICKS_CONFIG_FILE=/home/vsts/.databricks/config
            displayName: 'Configure Databricks CLI (manual path)'

          - script: |
              databricks workspace import /home/vsts/work/1/s/sample_notebook.py /Shared/sample_notebook --language PYTHON --format SOURCE --overwrite
            displayName: 'Upload Notebook to Databricks'
