trigger:
  paths:
    include:
      - notebooks/*

variables:
  - group: DatabricksSecrets

stages:
  - stage: DeployToDatabricks
    displayName: Deploy Notebooks to Databricks
    jobs:
      - job: Deploy
        displayName: Upload to Workspace
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'

          - script: |
              pip install databricks-cli
            displayName: 'Install databricks-cli'

          - script: |
              mkdir -p ~/.databricks
              echo -e "[DEFAULT]\nhost = $(DATABRICKS_HOST)\ntoken = $(DATABRICKS_TOKEN)" > ~/.databricks/config
            displayName: 'Configure Databricks CLI'

          - script: |
              databricks workspace import_dir "$(Build.SourcesDirectory)/notebooks" /Shared/notebooks --overwrite
            displayName: 'Upload Notebooks to Databricks'
