trigger:
  paths:
    include:
      - notebooks/*

variables:
  - group: DatabricksSecrets

stages:
  - stage: DeployToDatabricks
    displayName: Deploy Notebooks to Databricks
    jobs:
      - job: Deploy
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'

          - script: |
              pip install databricks-cli
            displayName: 'Install databricks-cli'

          - script: |
              databricks configure --token <<EOF
              $(DATABRICKS_HOST)
              $(DATABRICKS_TOKEN)
              EOF
            displayName: 'Configure Databricks CLI'

         - script: |
    databricks workspace import_dir "$(Build.SourcesDirectory)/notebooks" /Shared/notebooks --overwrite
  displayName: 'Upload Notebooks to Databricks'

